title: 'Cloud (paid)'
content: 'This device requires a paid subscription and a working internet connection to work.'
updated_by: 082753cc-9bb3-461d-9de0-42dab6bb9a8d
updated_at: 1718204486
blueprint: classification
