title: 'Battery (integrated)'
content: 'Devices powered by integrated lithium cells. Rechargeable but often not replaceable.'
updated_by: 082753cc-9bb3-461d-9de0-42dab6bb9a8d
updated_at: 1719056698
blueprint: power
