title: 'Battery (replaceable)'
content: 'Devices powered by standard replaceable batteries which are commonly available in rechargeable varieties such as Ni–Cd/Ni-MH AA/AAA batteries.'
updated_by: 082753cc-9bb3-461d-9de0-42dab6bb9a8d
updated_at: 1719056967
blueprint: power
