title: ONVIF
content: 'ONVIF is an open standard for the interface of physical IP-based security products.'
updated_by: 082753cc-9bb3-461d-9de0-42dab6bb9a8d
updated_at: 1730314644
blueprint: platform
