title: WiFi
content: 'Devices that connect to your WiFi network. Often form an access point for pairing. Sometimes require a cloud or app.'
updated_by: 082753cc-9bb3-461d-9de0-42dab6bb9a8d
updated_at: 1718377002
blueprint: datalink
