title: Eurom
content: |-
  [Eurom](https://eurom.nl/en/) have been developing and selling electrical products since 1974. These products are divided into seven main categories:

  - Cleaning
  - Garden & Recreation
  - Terrace heating
  - Permanent heating
  - Heating
  - Climate control
  - Aggregates
updated_by: 082753cc-9bb3-461d-9de0-42dab6bb9a8d
updated_at: 1730453141
blueprint: brand
